### ISSUE TITLE
Severity is highlighted even though it is set

### ISSUE THREAD

**Issue by bthrall** [nbp/meta-bugs#2]
For example, on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1874684 ):

![image](https://github.com/nbp/meta-bugs/assets/1091102/a23c4d38-4916-4514-8497-9496d9bee38d)

It also shows up correctly when the Severity is unset ("--").

**Comment by nbp** [comment]
The problem is caused by the fact bugzilla DOM got updated and the way to retreive the severity from the DOM no longer works.
